theme: minima
title: AI Viking Power
author: Marcus Erickson
description: I’m Marcus Erickson — a product strategist, software leader, and AI educator with 30+ years of experience. Through AI Viking Power, I help business owners and teams harness the power of AI to save time, sharpen communication, and grow smarter — not harder. Whether you're just curious about tools like ChatGPT or ready to integrate AI into your daily operations, I'm here to make it simple and useful.
